export const SET_TRACKS = 'SET_TRACKS';
export const SET_INDEX = 'SET_INDEX';
export const SET_SEARCHINPUT = 'SET_SEARCHINPUT';
export const SET_LOGINSTATUS = 'SET_LOGINSTATUS';
export const SET_LOGOUTBUTTONACTION = 'SET_LOGOUTBUTTONACTION';
export const SET_GENREMODE  = 'SET_GENREMODE';
export const SET_AMOUNTTRACKS  = 'SET_AMOUNTTRACKS';
export const SET_ISPLAYING  = 'SET_ISPLAYING';
